# fish completions for phantomgate

complete -c phantomgate -l domain -r -d 'Phishing domain name'
complete -c phantomgate -l phishlet -r -d 'Phishlet to activate'
complete -c phantomgate -l phishlet-dir -r -F -d 'Directory containing phishlet YAML files'
complete -c phantomgate -l config -r -F -d 'Path to config file'
complete -c phantomgate -l listen -r -d 'IP to bind listeners on'
complete -c phantomgate -l https-port -r -d 'HTTPS listener port'
complete -c phantomgate -l http-port -r -d 'HTTP redirect listener port'
complete -c phantomgate -l admin-port -r -d 'Operator dashboard port'
complete -c phantomgate -l admin-pass -r -d 'Operator dashboard password'
complete -c phantomgate -l cert -r -F -d 'TLS certificate file (PEM)'
complete -c phantomgate -l key -r -F -d 'TLS private key file (PEM)'
complete -c phantomgate -l store -r -F -d 'Path to data store file'
complete -c phantomgate -l list -d 'List available phishlets and exit'
complete -c phantomgate -l lure -r -d 'Create a lure URL for the specified victim info'
complete -c phantomgate -l intercept -d 'Enable DNS interception mode'
complete -c phantomgate -l wizard -d 'Launch interactive wizard for LAN interception setup'
complete -c phantomgate -l iface -r -d 'Network interface for interception'
complete -c phantomgate -l gateway -r -d 'Gateway IP for ARP poisoning'
complete -c phantomgate -l victim-ip -r -d 'Comma-separated victim IPs'
complete -c phantomgate -l poison-domain -r -d 'Comma-separated domains to poison'
complete -c phantomgate -l rogue-ap -d 'Create a rogue WiFi access point'
complete -c phantomgate -l ap-ssid -r -d 'SSID for the rogue AP'
complete -c phantomgate -l ap-pass -r -d 'WPA2 password for rogue AP'
complete -c phantomgate -l ap-channel -r -d 'WiFi channel for rogue AP'
complete -c phantomgate -l ap-iface -r -d 'WiFi interface for AP'
complete -c phantomgate -l use-ca -d 'Generate dynamic TLS certificates signed by a local CA'
complete -c phantomgate -l captive-portal -d 'Enable captive portal for CA cert distribution'
complete -c phantomgate -l version -d 'Print version and exit'
complete -c phantomgate -l generate-completions -r -d 'Generate shell completion script'
complete -c phantomgate -l dry-run -d 'Test configuration without binding ports'
complete -c phantomgate -l json-log -d 'Enable JSON structured logging'
complete -c phantomgate -l help -d 'Show help'
